Repository T3-FindIt/FindIt, pull requests merged in 2023-03, with the labels that each got.

#21 Style checker v2.1
  Code Standaard.MD
  StyleChecker/modules/C/Checker.py
  StyleChecker/modules/CPP/Checker.py
Labels: documentation, enhancement

#22 Google test integratie
  Templates/README.md
  Templates/Template - Unit Test CMake/CI.yml
  Templates/Template - Unit Test CMake/CMakeLists.txt
  Templates/Template - Unit Test CMake/test/CMakeLists.txt
  Templates/Template - Unit Test CMake/test/gtest_validation_test.cpp
  Templates/Template - Unit Test Embedded/platformio.ini
  Templates/Template - Unit Test Embedded/test/gtest.cpp
  Templates/Template - Unit Test Embedded/workflow.yml
Labels: documentation, enhancement

#24 Style Checker Hotfix
  StyleChecker/modules/C/Checker.py
  StyleChecker/modules/CPP/Checker.py
Labels: bug

#25 Test Files no Warning for missing header.
  StyleChecker/StyleChecker.py
  StyleChecker/modules/logger/logger.py
Labels: enhancement

#27 Wi fi protocol design
  Designs/WiFi Protocol/README.md
  Designs/WiFi Protocol/WiFiProtocol.wsd
  Designs/WiFi Protocol/WiFiProtocolHeartBeat.png
  Designs/WiFi Protocol/WiFiProtocolNotify.png
  Designs/WiFi Protocol/WiFiProtocolRequestMessages.png
  Designs/WiFi Protocol/WiFiProtocolSequence-page1.png
  Designs/WiFi Protocol/WiFiProtocolSequence-page2.png
  Designs/WiFi Protocol/WiFiProtocolSequence-page3.png
  Designs/WiFi Protocol/WiFiProtocolSignIn.png
Labels: documentation

#28 I2C protocol
  Designs/I2C Protocol/Design.wsd
  Designs/I2C Protocol/README.md
  Designs/I2C Protocol/RequestData.png
  Designs/I2C Protocol/SendData.png
Labels: documentation
