Repository T3-FindIt/FindIt, pull requests merged in 2023-05, with the labels that each got.

#81 Changed run triggers
  .github/workflows/CI.yml
  .github/workflows/hygiene.yml
Labels: enhancement

#85 Esp json
  .github/workflows/CI.yml
  Source/Master/.vscode/settings.json
  Source/Master/lib/Communication Abstraction/IMasterSlave.hpp
  Source/Master/lib/Communication Abstraction/IServerHandler.hpp
  Source/Master/lib/I2C/I2C.cpp
  Source/Master/lib/I2C/I2C.hpp
  Source/Master/lib/JsonBuilder/JsonBuilder.cpp
  Source/Master/lib/JsonBuilder/JsonBuilder.hpp
  Source/Master/lib/JsonBuilder/json.hpp
  Source/Master/lib/Websocket/WebSocketHandler.cpp
  Source/Master/lib/Websocket/WebSocketHandler.hpp
  Source/Master/lib/WiFi/WiFiHandler.cpp
  Source/Master/lib/WiFi/WiFiHandler.hpp
  Source/Master/platformio.ini
  Source/Master/src/JsonBuilder.cpp
  Source/Master/test/gtest.cpp
Labels: enhancement

#90 Fix/neg int stylechecker false positive fix
  StyleChecker/modules/C/Checker.py
  StyleChecker/modules/CPP/Checker.py
Labels: bug, StyleChecker

#91 Warning for interfaces fix
  StyleChecker/StyleChecker.py
Labels: bug, StyleChecker

#94 Feature/cmake rework
  Source/Server/.vscode/settings.json
  Source/Server/CMakeLists.txt
  Source/Server/src/CMakeLists.txt
  Source/Server/src/Communication/CMakeLists.txt
  Source/Server/src/Communication/ClusterConnection/CMakeLists.txt
  Source/Server/src/Communication/ClusterConnection/IClusterConnection.hpp
  Source/Server/src/Communication/Communication.cpp
  Source/Server/src/Communication/Communication.hpp
  Source/Server/src/Communication/ProtocolParser/CMakeLists.txt
  Source/Server/src/Database/CMakeLists.txt
  Source/Server/src/Database/IDatabase.hpp
  Source/Server/src/Database/PlainFileDatabase.cpp
  Source/Server/src/Database/PlainFileDatabase.hpp
  Source/Server/src/Message/CMakeLists.txt
  Source/Server/src/Message/MessageQueue/CMakeLists.txt
  Source/Server/src/Object/CMakeLists.txt
  Source/Server/src/Object/Object.cpp
  Source/Server/src/Object/Object.hpp
  Source/Server/src/UserInterface/CMakeLists.txt
  Source/Server/src/main.cpp
Labels: enhancement

#97 Feature/object class tests
  Source/Server/test/CMakeLists.txt
  Source/Server/test/Object/CMakeLists.txt
  Source/Server/test/Object/ObjectTest.cpp
Labels: enhancement

#98 Feature/readme shields
  README.md
Labels: documentation

#99 feature/auto pr labeler
  .github/pr-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: enhancement

#102 doc/added gtest badge to readme
  README.md
Labels: documentation

#103 Feature/issue and pr templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/pull_request_template.md
Labels: enhancement

#105 added templates that exist in develop to branch
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/pull_request_template.md
Labels: enhancement

#106 doc/I2C Testing
  POCs/I2C/I2C-Master/.gitignore
  POCs/I2C/I2C-Master/.vscode/extensions.json
  POCs/I2C/I2C-Master/include/README
  POCs/I2C/I2C-Master/lib/README
  POCs/I2C/I2C-Master/platformio.ini
  POCs/I2C/I2C-Master/src/main.cpp
  POCs/I2C/I2C-Master/test/README
  POCs/I2C/I2C-Slave/.gitignore
  POCs/I2C/I2C-Slave/.vscode/extensions.json
  POCs/I2C/I2C-Slave/include/README
  POCs/I2C/I2C-Slave/lib/README
  POCs/I2C/I2C-Slave/platformio.ini
  POCs/I2C/I2C-Slave/src/main.cpp
  POCs/I2C/I2C-Slave/test/README
  POCs/I2C/README.md
Labels: documentation

#86 Node nfc reader
  POCs/NFC/NFC-reader-POC/platformio.ini
  POCs/NFC/NFC-writer-POC/platformio.ini
  Source/Node/.vscode/settings.json
  Source/Node/include/IReader.hpp
  Source/Node/include/MFRC522Reader.hpp
  Source/Node/platformio.ini
  Source/Node/src/I2CCommunication.cpp
  Source/Node/src/MFRC522Reader.cpp
  Source/Node/src/main.cpp
Labels: enhancement

#112 fix/added extremely cursed method to be case insensitive
  .github/workflows/CI.yml
Labels: bug

#110 Doc/team roles in readme
  README.md
Labels: documentation
