Repository T3-FindIt/FindIt, pull requests merged in 2023-02, with the labels that each got.

#1 Line lint implementatie
  .github/workflows/hygiene.yml
  .linelint.yml
Labels: enhancement

#4 Documentatie
  Code Standaard.MD
  Manifesto.MD
Labels: documentation

#5 Gitignore update
  .gitignore
Labels: enhancement

#6 Auto code style check workflow
  .github/workflows/hygiene.yml
  Code Standaard.MD
  StyleCheck.py
Labels: documentation, enhancement

#8 Auto merge checks
  .github/workflows/merge_checks.yml
Labels: enhancement

#12 afkorting hoofdstuk
  Code Standaard.MD
Labels: documentation

#13 Style check v1.2
  StyleCheck.py
Labels: enhancement

#19 Style checker v2
  .github/workflows/hygiene.yml
  Code Standaard.MD
  StyleCheck.py
  StyleChecker/StyleChecker.py
  StyleChecker/modules/C/Checker.py
  StyleChecker/modules/CPP/Checker.py
  StyleChecker/modules/PlantUml/Checker.py
  StyleChecker/modules/logger/logger.py
Labels: enhancement

#20 Hoofd readme inleiding update
  README.md
Labels: documentation
