Repository T3-FindIt/FindIt, pull requests merged in 2023-06, with the labels that each got.

#119 Object review implementation
  Source/Server/src/CMakeLists.txt
  Source/Server/src/Communication/ClusterConnection/IClusterConnection.hpp
  Source/Server/src/Communication/ProtocolParser/IProtocolParser.hpp
  Source/Server/src/Database/CMakeLists.txt
  Source/Server/src/Database/IDatabase.hpp
  Source/Server/src/Database/PlainFileDatabase.cpp
  Source/Server/src/Database/PlainFileDatabase.hpp
  Source/Server/src/ItemType/CMakeLists.txt
  Source/Server/src/ItemType/ItemType.cpp
  Source/Server/src/ItemType/ItemType.hpp
  Source/Server/src/Message/IMessage.hpp
  Source/Server/src/Object/CMakeLists.txt
  Source/Server/src/Object/Object.cpp
  Source/Server/src/Object/Object.hpp
  Source/Server/src/main.cpp
  Source/Server/test/CMakeLists.txt
  Source/Server/test/Database/CMakeLists.txt
  Source/Server/test/Database/DatabaseTest.cpp
  Source/Server/test/ItemType/CMakeLists.txt
  Source/Server/test/ItemType/ItemTypeTest.cpp
Labels: enhancement, Review

#120 Fix/ activate to activate
  Source/Server/src/Communication/ProtocolParser/JSONProtocolParser.cpp
  Source/Server/test/JSON/JSONTest.cpp
Labels: bug

#121 Feat/parser smart pointer
  Source/Server/src/Communication/ProtocolParser/IProtocolParser.hpp
  Source/Server/src/Communication/ProtocolParser/JSONProtocolParser.cpp
  Source/Server/src/Communication/ProtocolParser/JSONProtocolParser.hpp
  Source/Server/test/JSON/JSONTest.cpp
Labels: enhancement

#109 Nfc writer
  Source/NFC-Writer/.gitignore
  Source/NFC-Writer/.vscode/extensions.json
  Source/NFC-Writer/include/IWriter.hpp
  Source/NFC-Writer/include/MFRC522Writer.hpp
  Source/NFC-Writer/include/README
  Source/NFC-Writer/include/UARTInterface.hpp
  Source/NFC-Writer/lib/README
  Source/NFC-Writer/platformio.ini
  Source/NFC-Writer/src/MFRC522Writer.cpp
  Source/NFC-Writer/src/UARTInterface.cpp
  Source/NFC-Writer/src/main.cpp
  Source/NFC-Writer/test/README
Labels: enhancement

#124 Master Dynamic I2C Allocation
  Source/Master/lib/Communication Abstraction/IMasterSlave.hpp
  Source/Master/lib/I2C/I2C.cpp
  Source/Master/lib/I2C/I2C.hpp
  Source/Master/lib/WiFi/WiFiHandler.cpp
  Source/Master/src/main.cpp
  Source/Master/test/gtest.cpp
Labels: enhancement

#130 Feat/server component integration
  README.md
  Source/Server/CMakeLists.txt
  Source/Server/src/Communication/CMakeLists.txt
  Source/Server/src/Communication/ClusterConnection/IClusterConnection.hpp
  Source/Server/src/Communication/ClusterConnection/TCPConnection.cpp
  Source/Server/src/Communication/ClusterConnection/TCPConnection.hpp
  Source/Server/src/Communication/Communication.cpp
  Source/Server/src/Communication/Communication.hpp
  Source/Server/src/Database/PlainFileDatabase.cpp
  Source/Server/src/Database/PlainFileDatabase.hpp
  Source/Server/src/ItemType/ItemType.cpp
  Source/Server/src/ItemType/ItemType.hpp
  Source/Server/src/UserInterface/UserInterface.cpp
  Source/Server/src/UserInterface/UserInterface.hpp
  Source/Server/src/main.cpp
  Source/Server/test/Database/DatabaseTest.cpp
  Source/Server/test/ItemType/ItemTypeTest.cpp
  Source/SoftwareClient/.gitignore
  Source/SoftwareClient/.vscode/settings.json
  Source/SoftwareClient/CMakeLists.txt
  Source/SoftwareClient/main.cpp
  StyleChecker/modules/CPP/Checker.py
Labels: enhancement

#133 Doc/readme update end of semester
  README.md
Labels: documentation
