Repository T3-FindIt/FindIt, pull requests merged in 2023-04, with the labels that each got.

#30 Esp 32 diagrammen
  Designs/ESP-32/ClassDiagram.png
  Designs/ESP-32/Design.wsd
  Designs/ESP-32/ESP32_Schematic.pdf
  Designs/ESP-32/README.md
Labels: documentation

#32 Update README.md
  Designs/I2C Protocol/README.md
Labels: documentation

#33 Style checker hot fix 2
  StyleChecker/modules/C/Checker.py
  StyleChecker/modules/CPP/Checker.py
Labels: enhancement

#37 Style Checker Hotfix
  StyleChecker/StyleChecker.py
  StyleChecker/modules/C/Checker.py
  StyleChecker/modules/CPP/Checker.py
Labels: bug

#38 Documentation update
  .github/workflows/CI.yml
  Templates/README.md
  Templates/Template - Unit Test CMake/CI.yml
  Templates/Template - Unit Test Embedded/workflow.yml
Labels: documentation

#42 Fix Testing on Talking-Skeleton
  .github/workflows/CI.yml
  Designs/ESP-32/ClassDiagram.png
  Designs/ESP-32/Design.wsd
  POCs/NFC/NFC-reader-POC/.gitignore
  POCs/NFC/NFC-reader-POC/.vscode/extensions.json
  POCs/NFC/NFC-reader-POC/include/README
  POCs/NFC/NFC-reader-POC/lib/README
  POCs/NFC/NFC-reader-POC/platformio.ini
  POCs/NFC/NFC-reader-POC/src/main.cpp
  POCs/NFC/NFC-reader-POC/test/README
  POCs/NFC/NFC-writer-POC/.gitignore
  POCs/NFC/NFC-writer-POC/.vscode/extensions.json
  POCs/NFC/NFC-writer-POC/include/README
  POCs/NFC/NFC-writer-POC/lib/README
  POCs/NFC/NFC-writer-POC/platformio.ini
  POCs/NFC/NFC-writer-POC/src/main.cpp
  POCs/NFC/NFC-writer-POC/test/README
  POCs/NFC/readme.md
  StyleChecker/StyleChecker.py
  StyleChecker/modules/C/Checker.py
  StyleChecker/modules/CPP/Checker.py
  Templates/README.md
  Templates/Template - Unit Test CMake/CI.yml
  Templates/Template - Unit Test Embedded/workflow.yml
Labels: bug

#46 Changed from MSB to LSB based
  Designs/I2C Protocol/README.md
Labels: documentation

#56 Include guard naming convention fix
  Code Standaard.MD
  StyleChecker/modules/C/Checker.py
  StyleChecker/modules/CPP/Checker.py
Labels: documentation, enhancement

#57 Style checker bar update
  StyleChecker/StyleChecker.py
  StyleChecker/modules/logger/logger.py
Labels: enhancement

#54 Server design fix
  Designs/Server Design/ClassDiagram.png
  Designs/Server Design/Design.wsd
Labels: bug, documentation

#60 Code standard fix
  Code Standaard.MD
Labels: documentation
